/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Sheng Jun Ye",
  "tagline": "DevSecOps Engineer · Security-first desde el código",
  "favicon": "img/favicon.ico",
  "url": "http://localhost:80",
  "baseUrl": "/",
  "organizationName": "Illumidragui",
  "projectName": "devsecops-pipeline",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/home/sye/labs/website/kuberlab/devsecops-v5/sidebars.js"
        },
        "blog": {
          "showReadingTime": true
        },
        "theme": {
          "customCss": "/home/sye/labs/website/kuberlab/devsecops-v5/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/shield.svg",
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "navbar": {
      "title": "~/Illumidragui",
      "logo": {
        "alt": "Shield Logo",
        "src": "img/shield.svg"
      },
      "items": [
        {
          "to": "/portfolio",
          "label": "Portfolio",
          "position": "left"
        },
        {
          "to": "/infrastructure",
          "label": "Infrastructure",
          "position": "left"
        },
        {
          "to": "/blog",
          "label": "Security Blog",
          "position": "left"
        },
        {
          "type": "custom-langToggle",
          "position": "right"
        },
        {
          "href": "https://github.com/Illumidragui/devsecops-pipeline",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Navegación",
          "items": [
            {
              "label": "Experiencia",
              "href": "/#experience"
            },
            {
              "label": "Security Blog",
              "to": "/blog"
            }
          ]
        },
        {
          "title": "Security Tools",
          "items": [
            {
              "label": "Gitleaks",
              "href": "https://github.com/gitleaks/gitleaks"
            },
            {
              "label": "OWASP ZAP",
              "href": "https://www.zaproxy.org"
            },
            {
              "label": "Trivy",
              "href": "https://aquasecurity.github.io/trivy"
            },
            {
              "label": "SonarCloud",
              "href": "https://sonarcloud.io"
            },
            {
              "label": "Snyk",
              "href": "https://snyk.io"
            }
          ]
        },
        {
          "title": "Contacto",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/Illumidragui"
            },
            {
              "label": "LinkedIn",
              "href": "https://linkedin.com/in/shjye"
            }
          ]
        }
      ],
      "copyright": "Docker Image Tag: latest — © 2026 Sheng Jun Ye. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
