name: Deploy → Kubernetes (ArgoCD)

on:
  push:
    tags: ['v*']
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual deploy'
        required: true

jobs:
  security:
    uses: Illumidragui/.github/.github/workflows/_reusable.code-security.yml@main
    with:
      language: node
      run-tests: false
    secrets: inherit

  build:
    needs: security
    uses: Illumidragui/.github/.github/workflows/_reusable.build-static.yml@main
    with:
      site-url: https://shengjunye.me
    secrets: inherit

  container-security:
    needs: build
    uses: Illumidragui/.github/.github/workflows/_reusable.container-security.yml@main
    with:
      image-name: ghcr.io/illumidragui/syesite
    secrets: inherit

  deploy:
    needs: container-security
    uses: Illumidragui/.github/.github/workflows/_reusable.deploy-kubernetes.yml@main
    with:
      image-name: ghcr.io/illumidragui/syesite
      config-repo: Illumidragui/devsecops-k8s-config
      config-values-file: syesite/values.yaml
      helm-repo: Illumidragui/devsecops-helm
      helm-values-file: syesite-chart/values.yaml
    secrets: inherit
